// Legacy mock data — not used in any active page (DB-backed getPlaces() is the live source).
// Kept for reference and local dev without a DB connection.
import type { PlaceListItem } from "@/types/place";

export const MOCK_PLACES: PlaceListItem[] = [
  {
    id: "mock-1",
    nameKr: "카페 라빌",
    nameEn: "Cafe Lavil",
    category: "cafe",
    address: "대전 유성구 봉명로 12",
    phone: null,
    location: { lat: 36.362, lng: 127.356 },
    distanceMeters: 600,
    thumbnailUrl: null,
    indoor: "allowed",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "medium",
    leash: "unknown",
    muzzle: "unknown",
    caution: "음료 주문 필수",
    latestVerifiedAt: "2026.05.20",
    verificationMethod: "DM",
  },
  {
    id: "mock-2",
    nameKr: "하이어그라운드",
    nameEn: "Higher Ground",
    category: "cafe",
    address: "대전 유성구 궁동 123",
    phone: null,
    location: { lat: 36.364, lng: 127.354 },
    distanceMeters: 800,
    thumbnailUrl: null,
    indoor: "unknown",
    carrierStrollerPolicy: "required",
    maxDogSize: "small",
    leash: "unknown",
    muzzle: "unknown",
    caution: "의자 위 반려견 금지",
    latestVerifiedAt: "2026.05.20",
    verificationMethod: "DM",
  },
  {
    id: "mock-3",
    nameKr: "카페몽",
    nameEn: null,
    category: "cafe",
    address: "대전 서구 둔산동 456",
    phone: null,
    location: { lat: 36.351, lng: 127.387 },
    distanceMeters: 1400,
    thumbnailUrl: null,
    indoor: "allowed",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "small",
    leash: "required",
    muzzle: "unknown",
    caution: null,
    latestVerifiedAt: "2026.05.18",
    verificationMethod: "Phone",
  },
  {
    id: "mock-4",
    nameKr: "퍼피라운지",
    nameEn: "Puppy Lounge",
    category: "cafe",
    address: "대전 중구 대흥동 78",
    phone: null,
    location: { lat: 36.327, lng: 127.427 },
    distanceMeters: 2100,
    thumbnailUrl: null,
    indoor: "outdoor_only",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "large",
    leash: "unknown",
    muzzle: "unknown",
    caution: null,
    latestVerifiedAt: "2026.05.16",
    verificationMethod: "Website",
  },
  {
    id: "mock-5",
    nameKr: "브런치 앤 바크",
    nameEn: "Brunch & Bark",
    category: "restaurant",
    address: "대전 유성구 원신흥남로 55",
    phone: null,
    location: { lat: 36.360, lng: 127.350 },
    distanceMeters: 1100,
    thumbnailUrl: null,
    indoor: "allowed",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "medium",
    leash: "unknown",
    muzzle: "unknown",
    caution: "식사 시간 외 입장 제한",
    latestVerifiedAt: "2026.05.15",
    verificationMethod: "On-site",
  },
  {
    id: "mock-6",
    nameKr: "루프탑 비스트로",
    nameEn: "Rooftop Bistro",
    category: "restaurant",
    address: "대전 서구 탄방동 91",
    phone: null,
    location: { lat: 36.344, lng: 127.383 },
    distanceMeters: 1900,
    thumbnailUrl: null,
    indoor: "outdoor_only",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "large",
    leash: "unknown",
    muzzle: "unknown",
    caution: null,
    latestVerifiedAt: "2026.05.14",
    verificationMethod: "Phone",
  },
  {
    id: "mock-7",
    nameKr: "한밭수목원",
    nameEn: "Hanbat Arboretum",
    category: "travel",
    address: "대전 서구 둔산대로 169",
    phone: null,
    location: { lat: 36.350, lng: 127.384 },
    distanceMeters: 2800,
    thumbnailUrl: null,
    indoor: "outdoor_only",
    carrierStrollerPolicy: "not_required",
    maxDogSize: "large",
    leash: "required",
    muzzle: "unknown",
    caution: "배변봉투 지참",
    latestVerifiedAt: "2026.05.14",
    verificationMethod: "On-site",
  },
  {
    id: "mock-8",
    nameKr: "도그프렌들리 파크",
    nameEn: "Dog Friendly Park",
    category: "travel",
    address: "대전 유성구 도룡동 3-1",
    phone: null,
    location: { lat: 36.375, lng: 127.381 },
    distanceMeters: 2800,
    thumbnailUrl: null,
    indoor: "unknown",
    carrierStrollerPolicy: "unknown",
    maxDogSize: "medium",
    leash: "unknown",
    muzzle: "unknown",
    caution: null,
    latestVerifiedAt: "2026.05.12",
    verificationMethod: "Website",
  },
];
