// TODO: Korean strings in caution and verificationMethod fields will be replaced with enum/i18n keys after DB integration
import type { Place } from "@/types/place";

export const MOCK_PLACES: Place[] = [
  {
    id: 1,
    name: "카페 라빌",
    category: "cafe",
    area: "유성구",
    address: "대전 유성구 봉명로 12",
    distanceKm: 0.6,
    indoorAllowed: true,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium"],
    caution: "음료 주문 필수",
    verifiedAt: "2026.05.20",
    verificationMethod: "DM",
    lat: 36.362,
    lng: 127.356,
  },
  {
    id: 2,
    name: "하이어그라운드",
    category: "cafe",
    area: "유성구",
    address: "대전 유성구 궁동 123",
    distanceKm: 0.8,
    indoorAllowed: null,
    carrierRequired: true,
    dogSizesAllowed: ["small"],
    caution: "의자 위 반려견 금지",
    verifiedAt: "2026.05.20",
    verificationMethod: "DM",
    lat: 36.364,
    lng: 127.354,
  },
  {
    id: 3,
    name: "카페몽",
    category: "cafe",
    area: "서구",
    address: "대전 서구 둔산동 456",
    distanceKm: 1.4,
    indoorAllowed: true,
    carrierRequired: false,
    dogSizesAllowed: ["small"],
    caution: "목줄 필수",
    verifiedAt: "2026.05.18",
    verificationMethod: "전화",
    lat: 36.351,
    lng: 127.387,
  },
  {
    id: 4,
    name: "퍼피라운지",
    category: "cafe",
    area: "중구",
    address: "대전 중구 대흥동 78",
    distanceKm: 2.1,
    indoorAllowed: false,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium", "large"],
    caution: null,
    verifiedAt: "2026.05.16",
    verificationMethod: "홈페이지",
    lat: 36.327,
    lng: 127.427,
  },
  {
    id: 5,
    name: "브런치 앤 바크",
    category: "restaurant",
    area: "유성구",
    address: "대전 유성구 원신흥남로 55",
    distanceKm: 1.1,
    indoorAllowed: true,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium"],
    caution: "식사 시간 외 입장 제한",
    verifiedAt: "2026.05.15",
    verificationMethod: "방문 확인",
    lat: 36.360,
    lng: 127.350,
  },
  {
    id: 6,
    name: "루프탑 비스트로",
    category: "restaurant",
    area: "서구",
    address: "대전 서구 탄방동 91",
    distanceKm: 1.9,
    indoorAllowed: false,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium", "large"],
    caution: null,
    verifiedAt: "2026.05.14",
    verificationMethod: "전화",
    lat: 36.344,
    lng: 127.383,
  },
  {
    id: 7,
    name: "한밭수목원",
    category: "travel",
    area: "서구",
    address: "대전 서구 둔산대로 169",
    distanceKm: 2.8,
    indoorAllowed: false,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium", "large"],
    caution: "목줄 필수, 배변봉투 지참",
    verifiedAt: "2026.05.14",
    verificationMethod: "방문 확인",
    lat: 36.350,
    lng: 127.384,
  },
  {
    id: 8,
    name: "도그프렌들리 파크",
    category: "travel",
    area: "유성구",
    address: "대전 유성구 도룡동 3-1",
    distanceKm: 2.8,
    indoorAllowed: null,
    carrierRequired: false,
    dogSizesAllowed: ["small", "medium"],
    caution: null,
    verifiedAt: "2026.05.12",
    verificationMethod: "홈페이지",
    lat: 36.375,
    lng: 127.381,
  },
];
